# Generated by Django 5.2.13 on 2026-04-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('INQUILINO', 'Inquilino'), ('TECNICO', 'Técnico')], default='INQUILINO', help_text='Define el nivel de acceso al sistema.', max_length=15, verbose_name='Rol del usuario'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de teléfono'),
        ),
    ]
