# Generated by Django 5.2.13 on 2026-06-08 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_managers_remove_customuser_rol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('code', models.CharField(max_length=6, verbose_name='Código')),
                ('purpose', models.CharField(choices=[('PASSWORD_RESET', 'Recuperación de contraseña')], default='PASSWORD_RESET', max_length=20, verbose_name='Propósito')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Código de verificación',
                'verbose_name_plural': 'Códigos de verificación',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose', 'code'], name='accounts_em_email_8c97d6_idx')],
            },
        ),
    ]
