# Generated by Django 5.2.13 on 2026-06-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('PLOMERIA', 'Plomería'), ('ELECTRICIDAD', 'Electricidad'), ('INFRAESTRUCTURA', 'Infraestructura'), ('LIMPIEZA', 'Limpieza'), ('SEGURIDAD', 'Seguridad'), ('OTRO', 'Otro')], default='', help_text='Solo aplica para técnicos. Define su área de competencia.', max_length=20, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('INQUILINO', 'Residente'), ('TECNICO', 'Técnico')], default='INQUILINO', max_length=20, verbose_name='Rol'),
        ),
    ]
