# Generated by Django 5.2.13 on 2026-06-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_especialidad_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='max_carga_trabajo',
            field=models.PositiveIntegerField(default=10, help_text='Máximo de puntos de carga activa (ALTA=3, MEDIA=2, BAJA=1). Solo aplica para técnicos.', verbose_name='Límite de carga de trabajo'),
        ),
    ]
