# Generated by Django 5.2.13 on 2026-07-05 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_max_carga_trabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('tecnico', models.ForeignKey(limit_choices_to={'role': 'TECNICO'}, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Horario de Trabajo',
                'verbose_name_plural': 'Horarios de Trabajo',
                'ordering': ['dia_semana', 'hora_inicio'],
                'indexes': [models.Index(fields=['tecnico', 'dia_semana'], name='accounts_ho_tecnico_76d9c3_idx')],
                'unique_together': {('tecnico', 'dia_semana', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='TecnicoEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(choices=[('PLOMERIA', 'Plomería'), ('ELECTRICIDAD', 'Electricidad'), ('INFRAESTRUCTURA', 'Infraestructura'), ('LIMPIEZA', 'Limpieza'), ('SEGURIDAD', 'Seguridad'), ('OTRO', 'Otro')], max_length=20, verbose_name='Especialidad')),
                ('es_principal', models.BooleanField(default=False, help_text='Marca esta especialidad como la principal del técnico.', verbose_name='Es principal')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidades_tecnico', to=settings.AUTH_USER_MODEL, verbose_name='Técnico')),
            ],
            options={
                'verbose_name': 'Especialidad del Técnico',
                'verbose_name_plural': 'Especialidades de Técnicos',
                'ordering': ['-es_principal', 'especialidad'],
                'unique_together': {('tecnico', 'especialidad')},
            },
        ),
    ]
