version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: inmo_db
    environment:
      - POSTGRES_DB=inmo_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mundo123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: inmo_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: inmo_n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=America/Guayaquil
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:
  n8n_data:
