# Generated by Django 5.2.13 on 2026-04-28 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre del edificio')),
                ('codigo', models.CharField(help_text='Identificador corto único, ej. "EDI-A01".', max_length=20, unique=True, verbose_name='Código interno')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('ciudad', models.CharField(default='Guayaquil', max_length=80, verbose_name='Ciudad')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Edificio',
                'verbose_name_plural': 'Edificios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número/identificador')),
                ('piso', models.PositiveSmallIntegerField(default=0, verbose_name='Piso')),
                ('tipo', models.CharField(choices=[('DEPARTAMENTO', 'Departamento'), ('LOCAL', 'Local Comercial'), ('OFICINA', 'Oficina'), ('CASA', 'Casa'), ('BODEGA', 'Bodega')], default='DEPARTAMENTO', max_length=20, verbose_name='Tipo')),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Área (m²)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activa')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='properties.edificio', verbose_name='Edificio')),
                ('inquilino', models.OneToOneField(blank=True, limit_choices_to={'role': 'INQUILINO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidad_asignada', to=settings.AUTH_USER_MODEL, verbose_name='Inquilino asignado')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'ordering': ['edificio__nombre', 'piso', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('edificio', 'numero'), name='unique_unidad_por_edificio')],
            },
        ),
    ]
