# Generated by Django 5.2.13 on 2026-06-03 23:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.PositiveIntegerField(verbose_name='Índice')),
                ('contenido', models.TextField(verbose_name='Contenido del fragmento')),
                ('embedding', models.JSONField(default=list, help_text='Vector numérico generado por Gemini text-embedding-004.', verbose_name='Embedding')),
                ('token_count', models.PositiveIntegerField(default=0, verbose_name='Tokens estimados')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fragmento de conocimiento',
                'verbose_name_plural': 'Fragmentos de conocimiento',
                'ordering': ['documento', 'indice'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('categoria', models.CharField(choices=[('PLOMERIA', 'Plomería'), ('ELECTRICIDAD', 'Electricidad'), ('SEGURIDAD', 'Seguridad'), ('REGLAMENTO', 'Reglamento'), ('GENERAL', 'General')], default='GENERAL', max_length=20, verbose_name='Categoría')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('indexado', models.BooleanField(default=False, help_text='True cuando los chunks y embeddings ya fueron generados.', verbose_name='Indexado')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documento de conocimiento',
                'verbose_name_plural': 'Documentos de conocimiento',
                'ordering': ['categoria', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('CERRADA', 'Cerrada')], default='ACTIVA', max_length=10, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='tickets.ticket', verbose_name='Ticket vinculado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de chat',
                'verbose_name_plural': 'Sesiones de chat',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rol', models.CharField(choices=[('USUARIO', 'Usuario'), ('ASISTENTE', 'Asistente'), ('SISTEMA', 'Sistema')], max_length=12, verbose_name='Rol')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('estado_proceso', models.CharField(choices=[('COMPLETADO', 'Completado'), ('PENDIENTE', 'Pendiente'), ('ERROR', 'Error')], default='COMPLETADO', max_length=12, verbose_name='Estado de procesamiento')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadatos')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='ai_agent.chatsession')),
                ('chunks_usados', models.ManyToManyField(blank=True, related_name='mensajes', to='ai_agent.knowledgechunk', verbose_name='Fragmentos RAG utilizados')),
            ],
            options={
                'verbose_name': 'Mensaje de chat',
                'verbose_name_plural': 'Mensajes de chat',
                'ordering': ['creado_en'],
            },
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_agent.knowledgedocument'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['usuario', 'estado'], name='ai_agent_ch_usuario_b0a6cc_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sesion', 'creado_en'], name='ai_agent_ch_sesion__00ef3b_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['estado_proceso'], name='ai_agent_ch_estado__4076cf_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['documento'], name='ai_agent_kn_documen_f280e2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgechunk',
            unique_together={('documento', 'indice')},
        ),
    ]
