# Generated by Django 5.2.13 on 2026-06-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgechunk',
            name='embedding',
            field=models.JSONField(default=list, help_text='Vector numérico generado por Gemini gemini-embedding-001.', verbose_name='Embedding'),
        ),
    ]
