# Generated by Django 5.2.13 on 2026-04-28 01:09

import apps.tickets.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('categoria', models.CharField(blank=True, choices=[('PLOMERIA', 'Plomería'), ('ELECTRICIDAD', 'Electricidad'), ('INFRAESTRUCTURA', 'Infraestructura'), ('LIMPIEZA', 'Limpieza'), ('SEGURIDAD', 'Seguridad'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Categoría')),
                ('estado', models.CharField(choices=[('CREADO_PENDIENTE_IA', 'Creado · Pendiente IA'), ('ANALIZADO_POR_IA', 'Analizado por IA'), ('PENDIENTE_VALIDACION', 'Pendiente Validación'), ('ASIGNADO', 'Asignado'), ('EN_CAMINO', 'En Camino'), ('EN_PROGRESO', 'En Progreso'), ('RESUELTO', 'Resuelto'), ('CANCELADO', 'Cancelado')], default='CREADO_PENDIENTE_IA', max_length=30, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('ia_descripcion_tecnica', models.TextField(blank=True, verbose_name='Descripción técnica IA')),
                ('ia_categoria_sugerida', models.CharField(blank=True, max_length=20, verbose_name='Categoría sugerida IA')),
                ('ia_prioridad_sugerida', models.CharField(blank=True, max_length=10, verbose_name='Prioridad sugerida IA')),
                ('ia_razon_asignacion', models.TextField(blank=True, verbose_name='Razón asignación IA')),
                ('ia_confianza', models.DecimalField(blank=True, decimal_places=2, help_text='Valor 0.00 – 1.00 reportado por el modelo.', max_digits=3, null=True, verbose_name='Confianza IA')),
                ('notas_resolucion', models.TextField(blank=True, verbose_name='Notas de resolución')),
                ('resuelto_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ia_tecnico_sugerido', models.ForeignKey(blank=True, limit_choices_to={'role': 'TECNICO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_sugeridos_ia', to=settings.AUTH_USER_MODEL, verbose_name='Técnico sugerido IA')),
                ('inquilino', models.ForeignKey(limit_choices_to={'role': 'INQUILINO'}, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_creados', to=settings.AUTH_USER_MODEL, verbose_name='Inquilino')),
                ('tecnico', models.ForeignKey(blank=True, limit_choices_to={'role': 'TECNICO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Asignado')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='properties.unidad', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, choices=[('CREADO_PENDIENTE_IA', 'Creado · Pendiente IA'), ('ANALIZADO_POR_IA', 'Analizado por IA'), ('PENDIENTE_VALIDACION', 'Pendiente Validación'), ('ASIGNADO', 'Asignado'), ('EN_CAMINO', 'En Camino'), ('EN_PROGRESO', 'En Progreso'), ('RESUELTO', 'Resuelto'), ('CANCELADO', 'Cancelado')], max_length=30, verbose_name='Estado anterior')),
                ('estado_nuevo', models.CharField(choices=[('CREADO_PENDIENTE_IA', 'Creado · Pendiente IA'), ('ANALIZADO_POR_IA', 'Analizado por IA'), ('PENDIENTE_VALIDACION', 'Pendiente Validación'), ('ASIGNADO', 'Asignado'), ('EN_CAMINO', 'En Camino'), ('EN_PROGRESO', 'En Progreso'), ('RESUELTO', 'Resuelto'), ('CANCELADO', 'Cancelado')], max_length=30, verbose_name='Estado nuevo')),
                ('nota', models.TextField(blank=True, verbose_name='Nota')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transiciones_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Realizada por')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Transición de estado',
                'verbose_name_plural': 'Historial de estados',
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to=apps.tickets.models.evidencia_upload_path, verbose_name='Archivo')),
                ('momento', models.CharField(choices=[('REPORTE', 'Reporte inicial'), ('RESOLUCION', 'Resolución')], default='REPORTE', max_length=15, verbose_name='Momento')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_subidas', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
                'ordering': ['creado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['estado'], name='tickets_tic_estado_c74d8e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['prioridad'], name='tickets_tic_priorid_554483_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['inquilino'], name='tickets_tic_inquili_523382_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['tecnico'], name='tickets_tic_tecnico_8871b9_idx'),
        ),
    ]
