# Generated by Django 5.2.13 on 2026-07-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fecha_programada',
            field=models.DateField(blank=True, help_text='Fecha en la que el técnico visitará la unidad.', null=True, verbose_name='Fecha programada'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='hora_programada_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora fin programada'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='hora_programada_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora inicio programada'),
        ),
    ]
