# Generated by Django 5.2.13 on 2026-07-06 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_add_aprobado_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255, verbose_name='Mensaje')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo_alerta', models.CharField(choices=[('INFO', 'Informativo'), ('WARNING', 'Requiere Atención'), ('SUCCESS', 'Éxito'), ('ERROR', 'Crítico')], default='INFO', max_length=20, verbose_name='Tipo de Alerta')),
                ('leido', models.BooleanField(default=False, verbose_name='Leído')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='tickets.ticket')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creado_en'],
            },
        ),
    ]
